AddonId: Date_Importer_d0e7fb90-e74e-4955-b7bc-43a13339637e
Packages:
  - Version: 2.13
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-08-07
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.08.07_57c08120/Date_Importer_d0e7fb90-e74e-4955-b7bc-43a13339637e_2_13.pext
    Changelog:
    - 'Extension rewritten as a plugin and renamed extension to "Purchase Date Importer"'
    - 'Added window that contains actions to import or export licenses'
  - Version: 2.14
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-08-10
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.08.10_7d122a68/Date_Importer_d0e7fb90-e74e-4955-b7bc-43a13339637e_2_14.pext
    Changelog:
    - 'Updated localizations'
  - Version: 2.15
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-08-21
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.08.21_54d33423/Date_Importer_d0e7fb90-e74e-4955-b7bc-43a13339637e_2_15.pext
    Changelog:
    - 'Improved stability of internet downloads'
  - Version: 2.16
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-08-31
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.08.31_1935a6a1/Date_Importer_d0e7fb90-e74e-4955-b7bc-43a13339637e_2_16.pext
    Changelog:
    - 'Updated localizations'